### ISSUE TITLE
Can't trigger events on dynamically created channel

### ISSUE THREAD

**Issue by ararog** [patternoia/WebSocketRails-iOS#2]
I'm trying to send events to different channels which are created dynamically, as an example, I have one user which is subscriber of its own channel to receive events sent by other users, the same thing happens with every user of my server.

Is there a way to do this with WebSockerRails-iOS?

**Comment by ararog** [comment]
BTW, I can dispatch events from WebSocketRailsDispatcher without any problem, but when I try to trigger an event from WebSocketRailsChannel, even if the logic is defined on rails controller, nothing happens, can't see the event on logs.

**Comment by ararog** [comment]
I believe this issue is caused by recent changes on websocket-rails, after change the WebSocketRails-iOS to pass token received by websocket_rails.channel_token to all subsequent event calls  and fix connection id,  which changed its param name to connection_id as hex code value.

I'll be sending a pull request soon!

**Comment by patternoia** [comment]
Hi, @ararog,

I've merged your pull request. Please test it.

Regards,
pat.
